# Generated by Django 3.1.6 on 2021-02-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='radius',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='swipe',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Vip', 'Vip'), ('no limit', 'Premium')], default='Basic', max_length=14),
        ),
    ]
