# Generated by Django 3.1.6 on 2021-02-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210213_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='swipe',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
