version: "2"

services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=social_network
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
  migration:
    image: project_innowise_web
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
